steps:
  - name: 'gcr.io/cloud-builders/git'
    args:
      - clone
      - 'https://source.developers.google.com/p/${_PROJECT}/r/${_REPO_NAME}'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
          'deployment-manager',
          'deployments',
          'create',
          'newtwowxw',
          '--config',
          'cmdconfig.yaml',
        ]
options:
  substitutionOption: ALLOW_LOOSE
  
substitutions:
  _REPO_NAME: github_aarya9_cloudbuild
  _PROJECT: terraform-336010
